site_name: QCLargeScale
site_description: Hybrid solutions for scientific computing
site_url: https://qclargescale.github.io/qc-website/
repo_url: https://github.com/QCLargeScale/qc-website.git
repo_name: QCLargeScale

theme:
  name: material

  logo: assets/logo.png
  favicon: assets/favicon.png

  font:
    text: Inter
    code: JetBrains Mono

  features:
    - navigation.tabs
    - navigation.top
    - navigation.footer
    - navigation.sections
    - navigation.expand
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.action.edit
    - content.tabs.link
    - toc.follow

  palette:
    - scheme: default
      primary: teal
      accent: cyan
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    - scheme: slate
      primary: teal
      accent: cyan
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

plugins:
  - search

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/your-org
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - tables
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.snippets

nav:
  - Project: index.md
  - About:
      - Overview: about/index.md
      - Team: about/team.md
      - Partners: about/partners.md
  - Publications:
      - Overview: publications/index.md
  - Training:
      - Overview: training/index.md
  - Events:
      - Upcoming: events/index.md
